### ISSUE TITLE
Compose buffer does not inherit the room's input method.

### ISSUE THREAD

**Issue by vizs** [alphapapa/ement.el#16] opened 2021-08-06 16:41 UTC
The compose buffer does not actually inherit the room's input method.
To reproduce this, do the following:

1. Visit a room in ement.
2. Set the room's input method to tamil-itrans (C-x C-m C-\\
   tamil-itrans RET).
3. Press RET and type something.
4. Press C-c ' to switch to the compose buffer.
5. Notice how the compose buffer has NOT inherited the input method
   i.e., its input method is rfc1345 (U in modeline) instead of tamil-itrans.
6. Press C-x C-s to quit the compose buffer.
7. Press C-g to cancel the message.
8. The room's input method has changed to rfc1345.  This is unexpected
   as input methods are supposed to be buffer local.
9. Further invocation of _any_ minibuffer command makes it use the
   tamil-itrans method.  This should NOT happen.  M-x should not inherit
   the input method but it does.  To actually use it, you need to press C-\\
   to switch back to the default input method.

In essence, the input methods go out of sync.

Now, if you change the compose buffer's input method.  A different
behaviour is observed.  To reproduce:

1. Visit a room in ement.
2. Set the room's input method to tamil-itrans (C-x C-m C-\
   tamil-itrans RET).
3. Press RET and type something.
4. Press C-c ' to switch to the compose buffer.
5. Notice how the compose buffer has NOT inherited the input method
   i.e., its input method is rfc1345 instead of tamil-itrans.
6. Change the input method to TeX (C-x C-m C-\ C-\ TeX RET).
7. Press C-x C-s to quit the compose buffer.
8. Press C-g to cancel the message.
9. The room's input method has changed to TeX.  This is, again,
   unexpected as input methods are supposed to be buffer local.
10. Further invocation of send message makes it use the TeX method.
This is different from previous cases' 10 since now M-x does not use the
TeX method (this is the expected behaviour).

This is again unexpected since changing the input method of the
compose buffer should not change the room's input method.  There's an
extra C-\ in step 6 when changing the input method to disable the
tamil-itrans method.  Somehow switching to the compose buffer makes
EVERY minibuffer command use the input method.  

EDIT: I'll try to fix this tomorrow, as it is quite late right now.

**Comment by vizs** [comment] 2021-08-06 16:51
Stepping through `ement-room-compose-message' using edebug makes it work as expected...

**Comment by alphapapa** [comment] 2021-08-10 09:44
@vizs Thanks.  I think those commits should make it work as desired now.  Please let me know if it does.

**Comment by vizs** [comment] 2021-08-11 05:38
After the commit, ement no longer has the issue with input methods
going out of sync.  That is, the room's input method doesn't change to
something else when using the compose command.

However, the compose buffer only inherits the input method every other
time, literally.  And whenever the compose buffer does not inherit the
input method, every minibuffer command uses the room's input method.

To reproduce,

1. Start ement.
2. Switch input method to tamil-itrans i.e., C-x C-m C-\ tamil-itrans
RET.
3. Press RET and type something.
4. Press C-c ', notice that compose buffer has not inherited the input
method.
5. Press C-x C-s C-g to quit sending the message.
6. Press M-x, it will use the tamil-itrans method (this should not
happen).

If you repeat the same steps, the input method is inherited.  Do it
again, it doesn't...  I'm not sure how reliable this is however.

**Comment by alphapapa** [comment] 2021-08-11 06:08
> 2. Switch input method to tamil-itrans i.e., C-x C-m C-\ tamil-itrans RET. 3. Press RET and type something. 4. Press C-c ', notice that compose buffer has not inherited the input method.

The assumption that I've been making is that, if you `set-input-method` in a buffer and then call a function that reads from the minibuffer, the minibuffer will inherit `current-input-method`.  But maybe not?  I don't use input methods, so maybe you could find out what's going on here, I'd appreciate it.  It will probably be a simple fix once we understand what's going on.

**Comment by vizs** [comment] 2021-08-11 06:11
Your assumptions are right.  And currently there's no problem with the
minibuffer inherting the current input method.

And yes, I will see if I can fix it though I found all the jumps with
the compose buffer stuff quite confusing so you will have to give some
more time so that I can understand how the compose buffer stuff works.

**Comment by alphapapa** [comment] 2021-08-11 06:13
As far as I can tell, every time `read-from-minibuffer` is called from `ement-room-read-string`, we set the INHERIT-INPUT-METHOD argument to non-nil, so the minibuffer should inherit the input method of the room buffer.  But from what you're describing, it sounds like that's not the case.  I guess we need a way to check the value of `current-input-method` while in the minibuffer, but `M-:` doesn't work when the minibuffer is already open, so...

> Your assumptions are right.  And currently there's no problem with the
minibuffer inherting the current input method.

Okay, so the minibuffer *does* get the input method, and the problem is propagating it to the compose buffer?

**Comment by alphapapa** [comment] 2021-08-11 06:15
> And yes, I will see if I can fix it though I found all the jumps with the compose buffer stuff quite confusing so you will have to give some more time so that I can understand how the compose buffer stuff works.

No problem, the code is awkward because of needing to add self-removing hooks to do things.  Note as well that the hooks are closures that capture values bound immediately before their definitions, etc.  Thanks for your help with this.

**Comment by vizs** [comment] 2021-08-12 12:42
In ement-room-compose-from-minibuffer, you have the comment ";; HACK:
I can't seem to find a better way to do this, to exit the minibuffer
without exiting this command too."  I think there might be a "less
hacky" way to get around this by throw-ing 'exit with a function as the
VAL argument.  There are two problems with this approach however,
namely:

1. Unlike throwing 'exit with nil, throwing with VAL as a
function completes the current command i.e., the command does not abort
like it would if you ran abort-recursive-edit.
2. Following from 1, if we were to change
ement-room-compose-from-minibuffer to throw a function instead, then
we will have to store the state of the minibuffer in buffer local
variables so as to not send the current draft.  Storing state still looks like
an ugly approach to me, but you may have a different opinion.

Ref: docstring of recursive-edit and the Info node'(elisp)Recursive
Editing'.

**Comment by alphapapa** [comment] 2021-08-12 12:45
If we made those changes, what would the benefit be?

**Comment by vizs** [comment] 2021-08-12 12:49
For one, I think the function will be much easier to reason about.
Personally, I found it quite hard to get what was going on with regards
to the compose buffer mechanism when I read the relevant code.  I
believe this approach will be less fickle as well.

As for the bug report itself, I'm quite sure that this bug will be fixed
if we store the minibuffer's input-method as a buffer-local variable.
As of right now, I really do not know where the problem arises.

**Comment by alphapapa** [comment] 2021-08-12 12:55
> For one, I think the function will be much easier to reason about. Personally, I found it quite hard to get what was going on with regards to the compose buffer mechanism when I read the relevant code.  I believe this approach will be less fickle as well. 

I'd rather not change the code for the sake of changing the code.  If we make a change, it should be one that improves the behavior or solves a problem.

> As for the bug report itself, I'm quite sure that this bug will be fixed if we store the minibuffer's input-method as a buffer-local variable. As of right now, I really do not know where the problem arises.

We already store the minibuffer's input method here by binding it before closing the minibuffer:

https://github.com/alphapapa/ement.el/blob/b6263b1a792e126a5e2723acc155ca35bab58dc8/ement-room.el#L2267

And it's propagated to the compose buffer in the closure:

https://github.com/alphapapa/ement.el/blob/b6263b1a792e126a5e2723acc155ca35bab58dc8/ement-room.el#L2275

If something in those steps isn't working, we need to find out why.

**Comment by alphapapa** [comment] 2021-08-12 13:05
> Thanks, that clear things up a bit more.  I will look into it, and come up with a patch (hopefully).

Thanks.

> FWIW, I mostly wanted to let you know that there exists a way to write the function without hooks.

I'm not sure if that's accurate.  In the Elisp manual section on minibuffers, it seems to say that throwing only works while in a recursive edit, not just in any minibuffer.

**Comment by vizs** [comment] 2021-08-12 13:28
> I'm not sure if that's accurate. In the Elisp manual section on
> minibuffers, it seems to say that throwing only works while in a
> recursive edit, not just in any minibuffer.

I think it is.  From '(elisp)Recursive Editing',

    Minibuffer input is a special kind of recursive editing.  It has a
    few special wrinkles, such as enabling display of the minibuffer and the
    minibuffer window, but fewer than you might suppose.  Certain keys
    behave differently in the minibuffer, but that is only because of the
    minibuffer’s local map; if you switch windows, you get the usual Emacs
    commands.

This suggests that the top-most minibuffer will respond to throw regardless
of what `enable-recursive-minibuffers' is.  And this seems to be true,
try {C-c C-c} after eval'ing when in M-x:

    (defun vz/test-1 ()
      (interactive)
      (throw 'exit 'vz/test-2))

    (defun vz/test-2 ()
      (message "^EEEEEEEEEEEEEEE"))

    (define-key minibuffer-local-map (kbd "C-c C-c") #'vz/test-1)
    (setq enable-recursive-minibuffers nil)

**Closed** 2021-08-14 12:40 UTC
Labels: bug
