### ISSUE TITLE
Gaps from limited sync responses are not filled

### ISSUE THREAD

**Issue by vizs** [alphapapa/ement.el#35] opened 2021-08-30 05:13 UTC
I'm not sure if the current behaviour is intended.  Upon waking my suspended laptop and manually syncing a room with g, I expected ement to fetch all messages that I missed; but it only fetches the last few.  Currently on c4fff828a5542a61e9fee961b0307e253b0508bc.

**Comment by alphapapa** [comment] 2021-08-30 06:11
Yes, I'm aware of this.  AFAIK the issue is that we need to handle "limited" sync responses by retrieving events back until the previously seen token.  Thanks for reporting it so I'll be sure to remember.  ;)

**Comment by vizs** [comment] 2021-08-30 09:33
Thanks for looking into this!

**Comment by alphapapa** [comment] 2021-10-05 04:40
This was fixed by https://github.com/alphapapa/ement.el/commit/6d772ec70499d6ed80d55c5fa9dcbe43e6f33c45.  As long as gaps are <1,000 events, they will be filled now.  Beyond that, we could increase the limit or make it customizeable, but this is good enough for most situations; only very busy rooms will often exceed that limit.

**Comment by vizs** [comment] 2021-10-05 13:59
I'm not sure if 6d772ec introduced it but after updating Ement.el to get that commit in, sometimes messages would be rendered twice, specifically the _old_ ones that were present prior to sync IIRC.  I haven't been able to come up with a way to reproduce this behaviour.  I think what I'm witnessing here is what this NOTE says: https://github.com/alphapapa/ement.el/blob/1f499bed6b583165e7ee074317ed4c771cc24180/ement-room.el#L1050

**Comment by alphapapa** [comment] 2021-10-05 16:42
>  I think what I'm witnessing here is what this NOTE says:

That seems unlikely, unless you're doing what the rest of the note says.  :)  

I haven't seen this problem.  If you can find a way to reproduce this, please let me know.

(IIRC there may be a bug with duplicating certain events if a room's buffer is closed and reopened, but that's not related to this one.)

**Closed** 2022-05-29 16:31 UTC
