### ISSUE TITLE
Setting `ement-room-message-text` fontifies formatted bodies too

### ISSUE THREAD

**Issue by p00f** [alphapapa/ement.el#180] opened 2023-07-08 02:01 UTC
If I customize `ement-room-message-text`, it makes code blocks in formatted bodies use that (variable-pitch) font too, even when `ement-room-shr-use-fonts` is `t`.

This means there is no way to use variable-pitch fonts for normal (unformatted?) bodies without breaking formatted bodies

**Comment by phil-s** [comment] 2023-07-12 05:57
Duplicate of https://github.com/alphapapa/ement.el/issues/174 ?

**Comment by p00f** [comment] 2023-07-12 06:07
yes, thanks

**Closed** 2023-07-12 06:07 UTC
Labels: enhancement, help wanted, good first issue
